name: t20-fri-ray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
 - pip
 - numpy
 - scipy
 - pandas
 - scikit-learn
 - scikit-image
 - pytest
 - cudatoolkit >= 10.0 # on a non gpu machine and having trouble installing? comment this out
 - pytorch
 - torchvision
 - matplotlib
 - seaborn
 - pip:
   - tensorflow
   - tensorboard
   - aiohttp
   - psutil
   - jupyter
   - jupyterlab
   - tqdm
   - jupyter-tensorboard
   - ray[tune]
   - xgboost
   - boto3
